package table

type BorderType string

const (
	BorderTypeNil                    BorderType = "nil"
	BorderTypeNone                   BorderType = "none"
	BorderTypeSingle                 BorderType = "single"
	BorderTypeThick                  BorderType = "thick"
	BorderTypeDouble                 BorderType = "double"
	BorderTypeDotted                 BorderType = "dotted"
	BorderTypeDashed                 BorderType = "dashed"
	BorderTypeDotDash                BorderType = "dotDash"
	BorderTypeDotDotDash             BorderType = "dotDotDash"
	BorderTypeTriple                 BorderType = "triple"
	BorderTypeThinThickSmallGap      BorderType = "thinThickSmallGap"
	BorderTypeThickThinSmallGap      BorderType = "thickThinSmallGap"
	BorderTypeThinThickThinSmallGap  BorderType = "thinThickThinSmallGap"
	BorderTypeThinThickMediumGap     BorderType = "thinThickMediumGap"
	BorderTypeThickThinMediumGap     BorderType = "thickThinMediumGap"
	BorderTypeThinThickThinMediumGap BorderType = "thinThickThinMediumGap"
	BorderTypeThinThickLargeGap      BorderType = "thinThickLargeGap"
	BorderTypeThickThinLargeGap      BorderType = "thickThinLargeGap"
	BorderTypeThinThickThinLargeGap  BorderType = "thinThickThinLargeGap"
	BorderTypeWave                   BorderType = "wave"
	BorderTypeDoubleWave             BorderType = "doubleWave"
	BorderTypeDashSmallGap           BorderType = "dashSmallGap"
	BorderTypeDashDotStroked         BorderType = "dashDotStroked"
	BorderTypeThreeDEmboss           BorderType = "threeDEmboss"
	BorderTypeThreeDEngrave          BorderType = "threeDEngrave"
	BorderTypeOutset                 BorderType = "outset"
	BorderTypeInset                  BorderType = "inset"
	BorderTypeApples                 BorderType = "apples"
	BorderTypeArchedScallops         BorderType = "archedScallops"
	BorderTypeBabyPacifier           BorderType = "babyPacifier"
	BorderTypeBabyRattle             BorderType = "babyRattle"
)
